name: .NET Core

on: [push]

jobs:

  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Decrypt large secret
        run: ./decrypt_secret.sh
        env:
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
      - name: Test printing your secret (Remove this step in production)
        run: cp $HOME/secrets/cachesheet-accountservice.json ./test/CacheSheet.Tests.Interop/
        
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100'
    - name: Build with dotnet
      run: dotnet build --configuration Release
