name: CI

on: [push]

jobs:
  build:
    name: build, test & publish
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Decrypt large secret
      run: ./decrypt_secret.sh
      env:
        PASSPHRASE: ${{ secrets.PASSPHRASE }}
    - name: cp $HOME/secrets/cachesheet-accountservice.json ./test/CacheSheet.Tests.Interop/cachesheet-accountservice.json
      run: cp $HOME/secrets/cachesheet-accountservice.json $HOME/work/CacheSheet/CacheSheet/test/CacheSheet.Tests.Interop/
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100'
    - name: Build
      run: dotnet build --configuration Release --version-suffix prerelease-$(date +%Y%m%d%H%M%S)
    - name: Tests
      run: dotnet test
    - name: Publish nuget
      run: |
          for f in $HOME/work/CacheSheet/CacheSheet/src/CacheSheet/bin/Release/*.nupkg
          do
            dotnet nuget push  $f -k {{ secrets.NUGET_KEY }} -s https://api.nuget.org/v3/index.json
          done
      shell: bash

      # curl -vX PUT -u "etiennepierrot-nuget:${{ secrets.NUGET_KEY }}" -F package=@$f https://www.nuget.org/api/v2/package/etiennepierrot-nuget/
